sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
install:
  - composer self-update
  - composer install --no-interaction
before_script:
  - cd lib
  - wget http://www.smarty.net/files/Smarty-3.1.8.tar.gz
  - tar -xvzf Smarty-3.1.8.tar.gz > /dev/null 2>&1 &
  - mv Smarty-3.1.8/libs/ ./Smarty
  - wget http://downloads.sourceforge.net/project/phemto/phemto_0.1_alpha10.tar.gz
  - tar -xvzf phemto_0.1_alpha10.tar.gz > /dev/null 2>&1 &
  - pear install --alldeps HTTP
  - pear install --alldeps Translation2
  - pear install --alldeps --force XML_Serializer
  - pear channel-discover zend.googlecode.com/svn
  - pear install zend/zend
  - phpenv rehash
  - cd ..
script:
  - php script/test_all.php --verbose
